inlets/inlets

- Gopkg.lock
- README.md
- main.go
- parse_upstream.go
- vendor/github.com/twinj/uuid/.gitignore
- vendor/github.com/twinj/uuid/.travis.yml
- vendor/github.com/twinj/uuid/LICENSE
- vendor/github.com/twinj/uuid/README.md
- vendor/github.com/twinj/uuid/appveyor.yml
- vendor/github.com/twinj/uuid/format.go
- vendor/github.com/twinj/uuid/generator.go
- vendor/github.com/twinj/uuid/saver.go
- vendor/github.com/twinj/uuid/timestamp.go
- vendor/github.com/twinj/uuid/types.go
- vendor/github.com/twinj/uuid/uuid.go
- vendor/github.com/twinj/uuid/version.go
- allows upstream list to be provided by client (this is not
required on the server)
Signed-off-by: Alex Ellis <alexellis2@gmail.com>
> Allow upstream list

- Makefile
See #10 for requirements; this adds an arm64 target to the Makefile.
> Adds arm64 target to Makefile

- Dockerfile.runtime
- README.md
- pkg/server/server.go
- pkg/types/bus.go
PR:
- Synchronisation across go-routines request/responses
This is required at higher load, the code in master can deliver an incorrect response under very high concurrency, these changes fix that.
> Synchronisation

- README.md
- get.sh
> Add script for installation via curl

- README.md
**What**
- Bump the stats for the inlet 2.0 release announcement on hacker news
> Update 2.0 hackernews stats

- README.md
Signed-off-by: Ruan Bekker <ruan.ru.bekker@gmail.com>
Blog post on how Inlets helped me to expose my local endpoints from my homelab behind CGN
I have:
> Add Ruans inlets blogpost

- README.md
> add Banzai Cloud tweet about K8S Services

- README.md
Signed-off-by: Matevz Mihalic <matevz.mihalic@gmail.com>
Update version numbers and remove armhf references in readme.
Closes #111
I have:
> Update version numbers and remove armhf references

- ADOPTERS.md
Signed-off-by: Tobias Brunner <tobias.brunner@vshn.ch>
Add an ADOPTERS.md file to the project so that the world knows about the project usage and help others to see the potential of inlets.
Looked at the generated md file and it looks great.
-
I have:
> add an ADOPTERS.md file to show the world who is using inlets

- README.md
Signed-off-by: Matt Bacchi <mbacchi@gmail.com>
Add link to blog post on using EC2 with Inlets
I have:
> Add blog post on using EC2 with Inlets

- README.md
Updates README with links to guide and video from TBS episode on Crossplane, k3sup, inlets.
N/a
N/a
I have:
> Add Crossplane tutorial to README

- README.md
- README_CN.md
Closes #124.
None
None
I have:
> Translate Docs to Chinese

- get.sh
Signed-off-by: Vivek Singh <vivekkmr45@yahoo.in>
I have:
> Update grep command to ignore case

- docs/vps.md
Signed-off-by: Taichi Uchihara <contact@ucpr.dev>
Fix broken links in docs/vps.md.
None
None
I have:
> Fix broken links in docs/vps.md

- hack/provision-vultr.sh
Signed-off-by: Johan Siebens <johan.siebens@gmail.com>
Add a script to provision an endpoint on Vultr
Used the script to start an inlets server on a Vultr instance and tested the connection with a client
No impact
I have:
> Add script to provision an endpoint on Vultr

- Dockerfile
- main.go
Signed-off-by: Alex Ellis (OpenFaaS Ltd) <alexellis2@gmail.com>
Change logrus to output with date
Tested with Go binary, fixes: #173
No change required. Potentially a log ingestion rule could be removed.
> Change logrus to output with date

- README.md
Signed-off-by: Matt Bacchi <mbacchi@gmail.com>
I have:
> Update URL for Inlets exit node on EC2 blog post

- docs/community.md
This guide is based on https://github.com/ngxson/inlets-heroku
As discussed in https://github.com/inlets/inlets/issues/114 , the binary file will be downloaded using wget.
This guide shows how to deploy `inlets` to Heroku with click-to-deploy button.
Tested on Heroku (click-to-deploy), Linux and Windows
I have:
> Add to community guide

- docs/vps.md
Signed-off-by: imtoohard <imtoohard@foxmail.com>
I have:
> Update Caddy location

- README.md
- README_CN.md
Update the Chinese version README.
No
Not being impacted.
I have:
> Update the Chinese version README.

- .github/workflows/build.yaml
- .github/workflows/publish.yaml
Signed-off-by: Alex Ellis (OpenFaaS Ltd) <alexellis2@gmail.com>
Update to Go 1.15 for CI
Tested via CI
N/a
> Update to Go 1.15 for CI
