inlets/inlets

pkg/client/client.go

PR:
* Fix close response body pkg/client/client.go
On the previous code, because "defer" in the loop, `Body.Close()` seems to never release

Close response body

---

.gitignore
Dockerfile
Makefile
main.go
pkg/client/client.go

This PR ingests the version information from the git repo to the binary. After this PR, `-version` will print the information of the binary.
Manually test
No. It won't impact anything.
I have:

ingest the version info into the binary

---

hack/inlets.service

Signed-off-by: Richard Gee <richard@technologee.co.uk>
Moves the exe location in the service definition to match the location installed to by the get script.
Fixes #40
None - bugfix
I have:

Change the exe location in the service file

---

.travis.yml
ci/hashgen.sh

This approacth is the same as openfaas/faas-cli.
Also updated travis to be picked up on the releases page.
Closes #44 
Signed-off-by: Ken Fukuyama <kenfdev@gmail.com>
```bash
$ ./ci/hashgen.sh 
```
Results:
```bash
$ ll bin
total 57072
-rwxr-xr-x  1 ken.fukuyama  staff   7.2M Mar 12 18:03 inlets
-rwxr-xr-x  1 ken.fukuyama  staff   6.7M Mar 12 18:04 inlets-arm64
-rw-r--r--  1 ken.fukuyama  staff    83B Mar 12 18:04 inlets-arm64.sha256
-rwxr-xr-x  1 ken.fukuyama  staff   6.1M Mar 12 18:03 inlets-armhf
-rw-r--r--  1 ken.fukuyama  staff    83B Mar 12 18:04 inlets-armhf.sha256
-rwxr-xr-x  1 ken.fukuyama  staff   7.9M Mar 12 18:03 inlets-darwin
-rw-r--r--  1 ken.fukuyama  staff    84B Mar 12 18:04 inlets-darwin.sha256
-rw-r--r--  1 ken.fukuyama  staff    77B Mar 12 18:04 inlets.sha256
```
None. …

Produce SHA hashes of each binary

---

README.md
cmd/client.go
pkg/client/client.go
pkg/server/server.go
pkg/transport/pingpong.go

Attempting to resolve #42 by sending continual ping from each
client to keep connection alive.
Signed-off-by: Alex Ellis <alexellis2@gmail.com>
By running a client / server and monitoring output.
```
go build && ./inlets client --remote=localhost:80 --upstream=http://192.168.0.35:8080
2019/03/12 13:18:02 Upstream:  => http://192.168.0.35:8080
2019/03/12 13:18:02 connecting to ws://localhost:80/tunnel with ping=10s
2019/03/12 13:18:02 Ping duration: 10.000000s
2019/03/12 13:18:02 Connected to websocket: [::1]:57520
2019/03/12 13:18:02 Writing pings
2019/03/12 13:18:11 Ping sent
2019/03/12 13:18:11 PongHandler. Extend deadline.
```
The new flag `--ping` is also working with the default and override:
```
go build && ./inlets client --remote=localhost:80 --upstream=http://192.168.0.35:8080 …
```

Initial ping/pong attempt

---

README.md

This PR adds instructions on installation using `brew` following the merge of the `inlets` formula into homebrew-core.
https://github.com/Homebrew/homebrew-core/pull/38235
Tested on local OSX box.
New functionality, no impact to existing users.
I have:

Add brew install instructions for OSX

---

pkg/router/router.go

I setup inlets but it always returns 503 error event I specify a hostname.
According [StackOverflow](https://stackoverflow.com/questions/42921567/what-is-the-difference-between-host-and-url-host-for-golang-http-request) it should replace `req.URL.Host` to `req.Host` and it will be able to use `Host` HTTP request header.
Just compile it on localhost and check it works well.
I have:

Fix unable to lookup registered host

---

pkg/client/client.go

The header was set using `header.Set()` which led to overriding the headers for multiple upstreams, such that only the last one in the `--upstream` arguments is present in the header upstream. Fixing #67.
Simple fix, tested with re-running the client locally. I can provide more robust testing if needed.
Run inlet client with multiple `--upstream` arguments. They successfully print, and thus are stored in the map correctly, i.e.
```
2019/06/05 13:29:17 Upstream: test.example.com => http://127.0.0.1:12435
2019/06/05 13:29:17 Upstream: test2.example.com => http://127.0.0.1:54321
```
but when the headers are printed, only one is included:
```
map[X-Inlets-Id:[XXXXXXXXXXXXXXXXXXXXXX] X-Inlets-Upstream:
[test2.example.com=http://127.0.0.1:54321] Authorization:[Bearer XXXXXXXXXXXXXXX]]
```
after …

Fix handling multiple upstreams

---

README.md
cmd/server.go
pkg/server/server.go

We have noticed that CORS related headers, like Access-Control-Allow-Origin, are stripped out of the responses. When investigating, I found that the k8s.io/apimachinery/pkg/util/proxy package's NewUpgradeAwareHandler does this on purpose, when the wrapTransport parameter is set to true - as is here in inlets.
This fixes #75 
When requesting a URL through the `server` that tunnels it through the `client` to an upstream, and if that upstream returns CORS headers, on the HTTP response received these headers are missing. With the new flag added when starting the `server`, those headers will be retained on the HTTP response.
The new flag is opt-in, existing users without configuration change (command line parameters) will have the same behavior as before.
I have:
I have not added any unit …

Add option to disable transport wrapping and keep CORS headers - fixes #75

---

README.md

CLOSES #79 
Update `inlets client` shell example to pass `--token` with previous line ending in ` \`
Ran example of `inlets client` as documented correctly in README and it now properly connects and passes token.
New users should now be able to follow readme and copy/paste examples will work.
I have:

Update README.md `inlets client` example to pass `--token` correctly

---

cmd/inlets.go
cmd/server.go
pkg/server/server.go

Signed-off-by: Alex Ellis (OpenFaaS Ltd) <alexellis2@gmail.com>
This patch means that users can split their control plane from the
data plane. The control plane is used for the tunnel and the data
plane is used to serve traffic to external users via the
exit-node's IP.
Tested with --port 80 --control-port 8080 and seeing that data
was not served on port 8080. Regression tested that when using
the same numeric value for both ports, the existing behaviour
was kept.
Fixes: #92 
No impact to existing users.
I have:

Add control-plane option

---

hack/provision-gcloud.sh

Add a script to provision a gcloud instance to run an inlets exit-node.
Script is hacky but has the same features as the DO one.
Manually tested a few times.
None.
I have:

Add a hacky script to provision an endpoint on gcp

---

README.md

Update example kube resources to the latest API version. Use standardised labels.
Manually, on GKE 1.13.
None.
I have:

Update kube yamls

---

README.md

The control plane is configured using the `--control-port` option instead of the `--control-plane` option
Signed-off-by: Tobias Brunner <tobias.brunner@vshn.ch>
The README says `--control-plane` where it actually is `--control-port`.
Inlets says:
```
Error: unknown flag: --control-plane
Usage:
inlets server [flags]
Flags:
-c, --control-port int             control port for tunnel (default 8080)
--disable-transport-wrapping   disable wrapping the transport that removes CORS headers for example
-h, --help                         help for server
-p, --port int                     port for server and for tunnel (default 8000)
--print-token                  prints the token in server mode (default true)
-t, --token string                 token for authentication
-f, --token-from string …
```

update control plane docs with correct option name

---

pkg/client/client.go

With this line present the token gets printed unintentionally which leads to an information disclosure
Signed-off-by: Tobias Brunner <tobias.brunner@vshn.ch>
This PR fixes #101 
Simple change :tm: 
See #101 
I have:

remove excess Println in client

---

Makefile

Docker build args are case sensitive. Otherwise docker build logs
`[Warning] One or more build-args [Version] were not consumed`
Signed-off-by: Tobias Brunner <tobias.brunner@vshn.ch>
The parameters passed to `--build-arg` need to have the same case as in the Dockerfile.
Before:
```
[...]
Step 19/19 : CMD ["--help"]
---> Running in a3b5257d2b66
Removing intermediate container a3b5257d2b66
---> 9bd1a0f44380
[Warning] One or more build-args [Version] were not consumed
Successfully built 9bd1a0f44380
[...]
```
After:
```
[...]
Step 19/19 : CMD ["--help"]
---> Running in 2d4522af6bc4
Removing intermediate container 2d4522af6bc4
---> a2d4ff4eeffd
Successfully built a2d4ff4eeffd
[..]
```
No migration needed. `make docker`, it just works :tm: 
I have:

Fix build arg for version string in Makefile

---

cmd/client.go
cmd/inlets.go
cmd/server.go

This PR streamlines the startup logging of inlets to always print the welcome message first even if there are errors later in the process.
Also reporting the version number and inlets component started helps the operator to exactly know what's going on.
Printing the welcome message like the other log lines unifies the output in a consistent way.
It has been tested locally, here are the outputs tested:
```
% go run main.go version
_       _      _            _
(_)_ __ | | ___| |_ ___   __| | _____   __
| | '_ \| |/ _ \ __/ __| / _` |/ _ \ \ / /
| | | | | |  __/ |_\__ \| (_| |  __/\ V /
|_|_| |_|_|\___|\__|___(_)__,_|\___| \_/
Version: dev
Git Commit: 
% go run main.go server 
2019/10/04 18:28:59 Welcome to inlets.dev! Find out more at https://github.com/alexellis/inlets
2019/10/04 18:28:59 …
```

improved startup logging with version information

---

contrib/nginx.md

I have added an explanation in the readme on how to configure nginx to proxy to inlets.
I have ran this configuration locally on my own raspberry pi. Attempted to connect over both ws:// and ws://
Not.
I have:

Added nginx configuration example to readme.

---

pkg/server/server.go
pkg/server/server_test.go

This PR switches to using crypto/subtle for token comparison.
I don't get to write Go too often and would love extra feedback.
Closes #109 
Manually and with unit tests.
Good token
Bad token
n/a
I have:

Use crypto subtle for constant time

---

.travis.yml
Dockerfile
Makefile

Build and publish multi-arch docker images; closes  #60
I've built the image and pushed it to `matevzmihalic/inlets:2.5.0-2-g769dfe8-dirty`.
I've ran the image on Packet ARM server and on my computer and it shows help and version just fine. I didn't try to run client or server, but I think it should work. 
I have:

Build multi-arch docker images

---

hack/provision-scaleway.sh

Signed-off-by: Flavio Meyer <flavio.meyer@flavio-meyer.ch>
Updating Ubuntu base image on Scaleway provision because it's currently not working [#118].
Mac OSX 10.15.
`./hack/provision-scaleway.sh`
Existing users aren't impacted. This fix is only for new inlets instances on Scaleway with auto provision bash script `./hack/provision-scaleway.sh`.
I have:

Updating Ubuntu base image on Scaleway provision

---

get.sh

Signed-off-by: Richard Gee <richard@technologee.co.uk>
The evaluation prior to moving the binary in get.sh was checking for the root user.  However, if the current user has sufficient privileges to write to the target location then there would be no reason not to attempt the move as the current user.
This change moves the if statement away from testing for the root user and instead checks for writability for the current location.
```sh
$ ls -ld /usr/local/bin
drwxrwxr-x  325 rgee0  staff  10400 22 Oct 20:10 /usr/local/bin
$ id -F
RGee0
$ ./get.sh
You already have the inlets cli!
Overwriting in 1 seconds.. Press Control+C to cancel.
Downloading package https://github.com/inlets/inlets/releases/download/2.6.1/inlets-darwin as /Users/rgee0/go/src/github.com/alexellis/inlets/inlets-darwin …
```

Switch to writable test in get.sh

---

get.sh

There was a notice to cancel download of the script if you had
it installed that was set to say you had 1 second to cancel.
We always install the latest version so if a user wants to
reinstall then its fine. The check has been removed.
Signed-off-by: Alistair Hey <alistair@heyal.co.uk>
There was a 1 second delay to cancel if a user already had the binary installed - It now just installs latest release onto their machine without the cancel in 1 second message
I have:

Remove notice about canceling download of script

---

.gitpod.yml
README.md

Signed-off-by: Nisar Hassan Naqvi <syednisarhassan12@gmail.com>
Hi! :slightly_smiling_face: 
This PR adds information and a little bit of config to simplify onboarding using Gitpod so that we can list the project on https://contribute.dev as asked by @alexellis 
You can try it out on my Fork of the Repo:
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/nisarhassan12/inlets)
It seems to work well!
After the merge of this PR the project will soon be listed on https://contribute.dev
fixes gitpod-io/contribute.dev#33
I have:

Simplifies Code Contributions by adding gitpod.

---

.gitpod.yml

This PR improves the setup of Gitpod workspaces for `inlet`. Upon workspace startup it runs `go get`, starts the inlet server and offers instructions how to connect to it. This way users can directly try inlets with an endpoint exposed to the internet.
I have opened a Gitpod workspace on my fork. To test these changes open this workspace: https://gitpod.io/#https://github.com/32leaves/inlets
Existing and new users have an easier time developing, and trying inlets.
No migration required.
I have:

[gitpod] Improve .gitpod.yml for a better Go setup

---

contrib/nginx.md

When using original configuration proposed here,  I couldn't figure out why why something like  `inlets client --remote wss://inlet.example.com --upstream="foo.example.com=http://127.0.0.1:8000"` --token=my_token wouldn't work. If I removed the host= and set `--upstream="http://127.0.0.1:8000"` everything was fine, and that is when I realized I needed to the send the host header along. Once this was added, the `--upstream="foo.example.com=http://127.0.0.1:8000"` would work.
updated config / restarted Nginx (nginx version: nginx/1.14.0 (Ubuntu)) running on Linode
restarted client and include host= in upstream and verified that curl works.
N/A  as this just a documentation update
I have:
- [X ] signed-off my commits with `git commit -s`
- [ N/A] added unit tests

Pass Host header to allow its use in --upstream

---

cmd/client.go
cmd/server.go

To help out beginners the code that parses a token file is now
forcing a trim of any new-lines.
Fixes: #154
Signed-off-by: Alex Ellis (OpenFaaS Ltd) <alexellis2@gmail.com>
Testing:
```
kosmos:inlets alex$ echo "pass" > /tmp/token
kosmos:inlets alex$ echo "" >> /tmp/token
kosmos:inlets alex$ cat /tmp/token
pass
kosmos:inlets alex$ ./inlets server --token-from /tmp/token
2020/02/04 08:57:40 Welcome to inlets.dev! Find out more at https://github.com/inlets/inlets
2020/02/04 08:57:40 Starting server - version dev
2020/02/04 08:57:40 Server token: "pass"
2020/02/04 08:57:40 Control Plane Listening on :8000
2020/02/04 08:57:40 Data Plane Listening on :8000
```

Trim new-lines from tokens

---

README.md

Updates README with link to guide
using minikube and free Cloud IP IKS
I created a free IKS cluster, then tested the tutorial step by step
No impact
I have:

Add iks+minikube tutorial to README

---

README.md
pkg/server/server.go
pkg/server/server_test.go

Signed-off-by: Simon Su <zsu801@aucklanduni.ac.nz>
- Closes #158, connection not established when a token is not provided (introduced in #110 - v2.5.1) 
- Minor changes to improve consistency of README.md.
Ran server and client locally w/ and w/o the --token flag to test connection and added a unit test.
Existing users on v2.5.1 later should not be affected as if a token is provided, as the behaviour will remain the same. However, this should partially unblock users bumping from an older version (w/o token).
I have:

Fixed connection not established when a token is not provided

---

cmd/server.go
pkg/server/server.go

Signed-off-by: Johan Siebens <johan.siebens@gmail.com>
Add option to select address to bind to.
Fixes #113 
Tested with Go binary, with IP addresses like eg 127.0.0.1
No impact, the new parameter is optional and the default value is the same as before
I have:

add option to select address to bind to

---

README.md
cmd/client.go
pkg/client/client.go
pkg/client/client_test.go
pkg/router/router.go

Enable strict filtering of upstream hosts in the client
There was an issue reported by a user about the allow code
which meant any host could be set by the server in a dial
request without any validation. This behaviour was as designed,
however some users may want a strict list of upstream hosts
to be the only ones that can be contacted.
Fixes: #165
Tested by hacking the server code to change the host being
dialed to one not specified by the client. This resulted in
a disconnect and denial of access.
Optional feature: off by default. It would make sense for most people to use this feature.
I have:

Enable strict filtering feature for client

---

get.sh

Signed-off-by: wingkwong <wingkwong.code@gmail.com>
support for downloading inlets into a folder with space.
Before:
```
test folder with space wingkwong$ ../get.sh 
../get.sh: line 69: [: too many arguments
Downloading package https://github.com/inlets/inlets/releases/download/2.7.0/inlets-darwin as /Users/wingkwong/Documents/GitHub/inlets/test folder with space/inlets
curl: (6) Could not resolve host: folder
curl: (6) Could not resolve host: with
curl: (6) Could not resolve host: space
```
After:
```
test folder with space wingkwong$ ../get.sh 
Downloading package https://github.com/inlets/inlets/releases/download/2.7.0/inlets-darwin as /Users/wingkwong/Documents/GitHub/inlets/test folder with space/inlets
Download complete.
Running with sufficient permissions to attempt to move inlets …
```

Support downloading into a folder with a space

---

README.md
README_CN.md

Signed-off-by: Jimmy song <rootsongjc@gmail.com>
`server.go` not exist on https://github.com/alexellis/hash-browns, its correct name is `main.go`.
I have:

doc: update sample program name

---

docs/vps.md

The instructions in the docs are for v1, and does not apply to v2 as directives such as `transparent` and `websockets` so no longer exists. Instead headers are used to use these features. 
Also, `proxy` has been renamed to `reverse_proxy` in v2. 
This pull request simply updates the docs with the proper setup for Caddy v2.
This was tested in a Google cloud f1-micro with Caddy versions `2.2.0-rc3` and `2.1.0`. The only files modified during testing was the `Caddyfile` which included the as documented headers setup and ran with `caddy run`. Inlets was ran as already documented. 
Testing was also conducted against both an express server and python built in http server and success from both.  
0
I have:

added setup info for caddy v2 in docs

---

cmd/server.go

it's impossible to change `data-addr` parameter, so PR should fix this
unable to expose insecure endpoint
I have:

server.go: data-addr parameter has no effect
